# -*- coding: utf-8 -*-
"""Despliegue Proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFWaO8izrWeuHG9Nnb3XXXqWevmkt3-f

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st

#Cargamos el modelo
import pickle
filename = 'modelo-clasificacion.pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))

#Interfaz Grafica
#Se crea interfaz gráfica con streamlit para captura de los datos


st.title('Predicción de que el estudiante va a desertar')
# 1. VECTORES DE VALORES ÚNICOS
v_semestre = [1, 2]
v_beneficio = ['MATRICULA', 'MATRICULA Y SOSTENIMIENTO', 'SOSTENIMIENTO']
v_genero = ['FEMENINO', 'MASCULINO']
v_subregion = ['BAJO CAUCA', 'MAGDALENA MEDIO', 'NORDESTE', 'NORTE', 'OCCIDENTE', 'ORIENTE', 'SUROESTE', 'URABA', 'VALLE DE ABURRA']
v_estrato = ['ESTRATO 1', 'ESTRATO 2', 'ESTRATO 3', 'ESTRATO 4', 'ESTRATO 5']
v_etnia = ['AFROCOLOMBIANO', 'INDIGENA', 'NINGUNO']
v_victima = ['NO', 'SI']
v_universidades = [
    'COLEGIO MAYOR DE ANTIOQUIA', 'COREDI', 'CORPORACION UNIVERSITARIA AMERICANA',
    'CORPORACION UNIVERSITARIA IBEROAMERICANA', 'CORPORACION UNIVERSITARIA MINUTO DE DIOS -UNIMINUTO-',
    'CORPORACION UNIVERSITARIA REMINGTON', 'CORPORACION UNIVERSITARIA U DE COLOMBIA',
    'ESCUELA NORMAL SUPERIOR MARIA AUXILIADORA', 'ESCUELA NORMAL SUPERIOR RAFAEL MARIA GIRALDO',
    'ESCUELA NORMAL SUPERIOR SAN PEDRO DE LOS MILAGROS', 'ESCUELA SUPERIOR TECNOLOGICA DE ARTES DEBORA ARANGO',
    'FUNDACION DE ESTUDIOS SUPERIORES UNIVERSITARIOS DE URABA ANTONIO ROLDAN BETANCUR',
    'FUNDACION ESCUELA COLOMBIANA DE MERCADOTECNIA -ESCOLME-', 'FUNDACION UNIVERSITARIA AUTONOMA DE LAS AMERICAS',
    'FUNDACION UNIVERSITARIA BELLAS ARTES', 'FUNDACION UNIVERSITARIA CATOLICA DEL NORTE',
    'FUNDACION UNIVERSITARIA CLARETIANA - UNICLARETIANA', 'FUNDACION UNIVERSITARIA ESUMER',
    'FUNDACION UNIVERSITARIA MARIA CANO', 'FUNDACION UNIVERSITARIA-CEIPA-',
    'INSTITUCION EDUCATIVA ESCUELA NORMAL SUPERIOR DE ABEJORRAL', 'INSTITUCION EDUCATIVA ESCUELA NORMAL SUPERIOR DE AMAGA',
    'INSTITUCION EDUCATIVA ESCUELA NORMAL SUPERIOR DE JERICO', 'INSTITUCION EDUCATIVA ESCUELA NORMAL SUPERIOR DEL BAJO CAUCA',
    'INSTITUCION EDUCATIVA ESCUELA NORMAL SUPERIOR DEL MAGDALENA MEDIO', 'INSTITUCION EDUCATIVA ESCUELA NORMAL SUPERIOR DEL NORDESTE',
    'INSTITUCION EDUCATIVA ESCUELA NORMAL SUPERIOR GENOVEVA DIAZ', 'INSTITUCION EDUCELA NORMAL SUPERIOR PEDRO JUSTO BERRIO',
    'INSTITUCION EDUCATIVA ESCUELA NORMAL SUPERIOR PRESBITERO JOSE GOMEZ ISAZA', 'INSTITUCION EDUCATIVA ESCUELA NORMAL SUPERIOR SAGRADA FAMILIA',
    'INSTITUCION EDUCATIVA ESCUELA NORMAL SUPERIOR SANTA TERESITA', 'INSTITUCION UNIVERSITARIA DE ENVIGADO',
    'INSTITUCION UNIVERSITARIA DIGITAL DE ANTIOQUIA', 'INSTITUCION UNIVERSITARIA MARCO FIDEL SUAREZ - IUMAFIS',
    'INSTITUCION UNIVERSITARIA PASCUAL BRAVO', 'INSTITUCION UNIVERSITARIA POLITECNICO GRANCOLOMBIANO',
    'INSTITUTO TECNOLOGICO METROPOLITANO', 'INSTIUCION EDUCATIVA NORMAL SUPERIOR SAN ROQUE',
    'NORMAL SUPERIOR MIGUEL ANGEL ALVAREZ', 'POLITECNICO COLOMBIANO JAIME ISAZA CADAVID',
    'SENA', 'TECNOLOGICO DE ANTIOQUIA', 'TECOC', 'UNIVERSIDAD AUTONOMA LATINOAMERICANA-UNAULA-',
    'UNIVERSIDAD CATOLICA DE ORIENTE', 'UNIVERSIDAD CATOLICA LUIS AMIGO-FUNLAM', 'UNIVERSIDAD CES',
    'UNIVERSIDAD COOPERATIVA DE COLOMBIA', 'UNIVERSIDAD DE ANTIOQUIA', 'UNIVERSIDAD DE MEDELLIN',
    'UNIVERSIDAD DE SAN BUENAVENTURA', 'UNIVERSIDAD EAFIT-', 'UNIVERSIDAD EIA',
    'UNIVERSIDAD NACIONAL ABIERTA Y A DISTANCIA', 'UNIVERSIDAD NACIONAL DE COLOMBIA',
    'UNIVERSIDAD PONTIFICIA BOLIVARIANA', 'UNIVERSIDAD SANTO TOMAS'
]
v_formacion = ['NORMALISTA', 'POSTGRADO', 'TECNICA PROFESIONAL', 'TECNOLOGICA', 'UNIVERSITARIA']
v_movilidad = [False, True]
v_am = ['NO', 'SI']

# 2. INTERFAZ DE USUARIO (WIDGETS)
col1, col2 = st.columns(2)

with col1:
    st.subheader("Filtros Personales")
    edad = st.slider('Edad', 13, 62, 20)
    genero = st.selectbox('Género', v_genero)
    estrato = st.selectbox('Estrato', v_estrato)
    etnia = st.selectbox('Grupo Étnico', v_etnia)
    victima = st.selectbox('¿Es víctima del conflicto?', v_victima)
    movilidad = st.selectbox('Se desplaza de su lugar de nacimiento?', v_movilidad)

with col2:
    st.subheader("Filtros Académicos")
    universidad = st.selectbox('Universidad', v_universidades)
    tipo_formacion = st.selectbox('Tipo de Formación', v_formacion)
    beneficio = st.selectbox('Beneficio', v_beneficio)
    semestre = st.selectbox('Semestre Convocatoria', v_semestre)
    residencia_am = st.selectbox('¿Reside en Área Metropolitana?', v_am)

st.divider()
#Dataframe
# Crear un diccionario con los nombres de las columnas del CSV original
input_data = {
    'SEMESTRE DE CONVOCATORIA': semestre,
    'BENEFICIO OTORGADO': beneficio,
    'GENERO': genero,
    'ESTRATO': estrato,
    'GRUPO ETNICO': etnia,
    'VICTIMA DEL CONFLICTO ARMADO': victima,
    'UNIVERSIDAD': universidad,
    'TIPO DE FORMACION': tipo_formacion,
    'edad_beneficiario': edad,
    'movilidad_territorial': movilidad,
    'Municipio_Residencia_Area_metropolitana': residencia_am
}

# Convertir a DataFrame
data = pd.DataFrame([input_data])

data

#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['SEMESTRE DE CONVOCATORIA', 'GENERO', 'movilidad_territorial'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

"""# Prediciones"""

# Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)

# Recorremos las predicciones y aplicamos la lógica
for prediccion in Y_pred:
    if prediccion == 1:
        print(f"Resultado {prediccion}: Es probable que se gradúe")
    else:
        print(f"Resultado {prediccion}: No se va a graduar")

data['Prediccion']=Y_pred
data.head()

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 9%")

